name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  library:
    name: Library Validation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [24.x, 26.x]
    steps:
      - name: Checkout Code 🛎️
        uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }} 🕸️
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Library Dependencies 💾
        run: yarn install
      - name: Build Library 🔧
        run: yarn build
      - name: Run Library Tests 🧪
        run: yarn test
  nestjs_app:
    name: NestJS Example App Validation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x, 26.x]
    steps:
      - name: Checkout Code 🛎️
        uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }} 🕸️
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Library Dependencies 💾
        run: yarn install
      - name: Build Library 🔧
        run: yarn build
      - name: Install NestJS Example App Dependencies 💾
        run: |
          cd ./examples/nestjs-mongoose-book-manager
          yarn install --force
      - name: Build NestJS Example App 🔧
        run: |
          cd ./examples/nestjs-mongoose-book-manager
          yarn build
      - name: Run NestJS Example App Tests 🧪
        run: |
          cd ./examples/nestjs-mongoose-book-manager
          yarn test
